### ISSUE TITLE
Questions from novices

### ISSUE THREAD

**Issue by cp319** [mli0603/stereo-transformer#1]
Hello, thank you for your open source code. It has been very helpful to me. But I have doubts about how to use "Pretrain". Especially how to import and run  the “pretrained” model. Thank you. Hope to get a reply

**Comment by mli0603** [comment]
Hello,

We have provided different examples of how to import and run the pretrained model in the [usage section](https://github.com/mli0603/stereo-transformer#usage), including Colab and terminal commands. Have you taken a look at that?

**Comment by 3dsf** [comment]
hey @mli0603,
I'm having issues with the script in the terminal window; @cp319 might be having the same.

When running `sh scripts/pretrain.sh`

> number of params in backbone: 1,050,800
> number of params in transformer: 797,440
> number of params in tokenizer: 503,728
> number of params in regression: 161,843
> Traceback (most recent call last):
>   File "main.py", line 250, in <module>
>     main(args_)
>   File "main.py", line 201, in main
>     data_loader_train, data_loader_val, _ = build_data_loader(args)
>   File "/home/ferg/git/stereo-transformer/dataset/__init__.py", line 26, in build_data_loader
>     dataset_train = SceneFlowFlyingThingsDataset(dataset_dir, 'train')
>   File "/home/ferg/git/stereo-transformer/dataset/scene_flow.py", line 80, in __init__
>     self._read_data()
>   File "/home/ferg/git/stereo-transformer/dataset/scene_flow.py", line 85, in _read_data
>     sub_folders = [os.path.join(directory, subset) for subset in os.listdir(directory) if
> FileNotFoundError: [Errno 2] No such file or directory: 'PATH_TO_SCENEFLOW/frame_finalpass/TRAIN'

---

When running the jupyter notebook 
`jupyter notebook scripts/inference_example.ipynb `
I can see that the pre-trained models are loaded from` ~/stereo-transformer/` -- >

> from the scrip# Load the pretrained model
> model_file_name = "../kitti_finetuned_model.pth.tar"
> checkpoint = torch.load(model_file_name)
> pretrained_dict = checkpoint['state_dict']
> model.load_state_dict(pretrained_dict)
> print("Pre-trained model successfully loaded.")
> Pre-trained model successfully loaded.

_this is where I have the pretrained models_  

---
---

**Note** 

- On the main git page you have a link for the pretrained models under the **Pre-trained Models** header, which work.  But then you have 2 links under the **Usage** header that are dead links.  

- `torchvision` should be included in your `requirements.txt`

**Interesting project and I'm looking forward to exploring it further**

**Comment by cp319** [comment]
> Hello,
> 
> We have provided different examples of how to import and run the pretrained model in the [usage section](https://github.com/mli0603/stereo-transformer#usage), including Colab and terminal commands. Have you taken a look at that?

thanks, I get it

**Comment by mli0603** [comment]
hello @3dsf, thanks for the notes. I have made some changes to README.md to clarify things a little bit.

> When running `sh scripts/pretrain.sh`
> 
> > number of params in backbone: 1,050,800
> > number of params in transformer: 797,440
> > number of params in tokenizer: 503,728
> > number of params in regression: 161,843
> > Traceback (most recent call last):
> > File "main.py", line 250, in 
> > main(args_)
> > File "main.py", line 201, in main
> > data_loader_train, data_loader_val, _ = build_data_loader(args)
> > File "/home/ferg/git/stereo-transformer/dataset/**init**.py", line 26, in build_data_loader
> > dataset_train = SceneFlowFlyingThingsDataset(dataset_dir, 'train')
> > File "/home/ferg/git/stereo-transformer/dataset/scene_flow.py", line 80, in **init**
> > self._read_data()
> > File "/home/ferg/git/stereo-transformer/dataset/scene_flow.py", line 85, in _read_data
> > sub_folders = [os.path.join(directory, subset) for subset in os.listdir(directory) if
> > FileNotFoundError: [Errno 2] No such file or directory: 'PATH_TO_SCENEFLOW/frame_finalpass/TRAIN'

The error here is that the argument `dataset_directory` is set to `PATH_TO_SCENEFLOW`, which is supposed to be replaced by the directory to Scene Flow data. The instruction was not clear. I now add a note to ask people to replace this manually in the [Terminal Example](https://github.com/mli0603/stereo-transformer/blob/main/README.md#terminal-example).

> When running the jupyter notebook
> `jupyter notebook scripts/inference_example.ipynb `
> I can see that the pre-trained models are loaded from` ~/stereo-transformer/` -- >
> 
> > from the scrip# Load the pretrained model
> > model_file_name = "../kitti_finetuned_model.pth.tar"
> > checkpoint = torch.load(model_file_name)
> > pretrained_dict = checkpoint['state_dict']
> > model.load_state_dict(pretrained_dict)
> > print("Pre-trained model successfully loaded.")
> > Pre-trained model successfully loaded.
> 
> _this is where I have the pretrained models_

Ah yes, the pretrained model is assumed to be in `stereo-transformer` folder, I added a note to clarify this in [Colab/Notebook Example](https://github.com/mli0603/stereo-transformer/blob/main/README.md#colabnotebook-example)

> **Note**
> 
> * On the main git page you have a link for the pretrained models under the **Pre-trained Models** header, which work.  But then you have 2 links under the **Usage** header that are dead links.

Thanks for pointing this out. It is fixed now. 

> * `torchvision` should be included in your `requirements.txt`

I thought about this, but end up not including it... 
Because PyTorch depends on the cuda version, so I cannot really add `torch` to requirements. Therefore I explicitly ask people to install PyTorch [here](https://github.com/mli0603/stereo-transformer#dependencies). Then if you look at the PyTorch installation command, it is something like `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`, where `torchvision` is included. Therefore I left out the `torchvision` in the requirements. I hope this makes sense.
