### ISSUE TITLE
Question about tokenizer.

### ISSUE THREAD

**Issue by HyoKong** [mli0603/stereo-transformer#2]
Thank you very much for your code and excellent job. Could you please explain more about the Tokenizer? I haven't found any introduction to the Tokenizer in your paper. Thank you very much for your help!

**Comment by mli0603** [comment]
Hi @HyoKong, it is the decoding path of feature extractor, which generates a feature descriptor map with the same resolution of the input. I used the name “tokenizer” in view of the term “language tokens” in NLP task.

**Comment by HyoKong** [comment]
Thank you for your reply. Could you please explain more about how to apply the attention weight to the raw images? There are many operations in the Regression Head. But it seems that there are few detailed introductions about the regression head in your paper. Thank you very much for your detailed explanation.

**Comment by mli0603** [comment]
Hi @HyoKong, I have added additional documentation to clarify things a bit [here](https://github.com/mli0603/stereo-transformer/blob/main/module/regression_head.py#L219). Not all details are mentioned in the paper due to space constraint. So we only include things that we feel are crucial to understand the pipeline. Have you looked at the documentation of each function in `regression_head`? Which one are you confused about? I can always add more information to clarify.

To answer your question
> Could you please explain more about how to use the attention weight to regress disparity and occlusion mask?

**Disparity**: attention weight is used to find the most attended pixel and build a 3px window around it to regress disparity, as outlined [here](https://github.com/mli0603/stereo-transformer/blob/main/module/regression_head.py#L39). The weighted-sum is to produce sub-pixel disparity values.
**Occlusion**: the attention weight within the 3px window naturally reflect the confidence, therefore the inverse of it is used to predict occlusion, as outlined [here](https://github.com/mli0603/stereo-transformer/blob/main/module/regression_head.py#L207)
These are in paper Section 3.2.5.
