### ISSUE TITLE
How much cuda memory is needed to run inference?

### ISSUE THREAD

**Issue by kadirbeytorun** [mli0603/stereo-transformer#3]
Hello, thank you for your great work

When I tried to run inference with "kitti_finetuned_model", I got "cuda ran out of memory" error.
My laptop has 4gb gpu memory, I thought it would be enough just to try out inference.

I tried decreasing batch size to 1, but result is still the same.

Could you guide me in the right direction to solve this issue?

Regards

**Comment by mli0603** [comment]
Hi @kadirbeytorun, 4GB memory unfortunately is not enough for fine-tuning on KITTI dataset. I would suggest a 16GB GPU for fine-tuning for batch-size of 1 (requirement is around 13GB). I hope this helps.

**Comment by mli0603** [comment]
Hi @kadirbeytorun, I realized that I misread your question previously. I appologize for that.

For inference on KITTI, based on my experiment, it requires 11GB memory. If you cannot run the algorithm due to limited memory on your local machine, I recommend you to checkout the [colab example](https://colab.research.google.com/github/mli0603/stereo-transformer/blob/main/scripts/inference_example_colab.ipynb). I have tested it and verifed that it works.

On that note, I have to admit that I did not optimize the script to reduce memory requirement. I am loading many inputs and saving a lot of intermidiate outputs on GPU, which can be removed. As an example, you don't have to load disparity/occlusion mask if you are just inferencing. You also don't have to output the `gt_response` from [here](https://github.com/mli0603/stereo-transformer/blob/main/module/regression_head.py#L250) etc  (the intermidiate outputs used for training). I hope this helps.

**Comment by kadirbeytorun** [comment]
Thank you Max, I really appreciate it. I could try using it on colab cloud, but the fact remains that in the end I aim to use this solution in an embedded environment with resource limitations, so I think a network requiring 10+GB gpu memory is not suitable for me :)

**Comment by mli0603** [comment]
I will try to take another look to see exactly how much memory the network requires after removing the intermidiate outputs. However, I doubt it will reduce to 4GB unfortunately.

**Comment by mli0603** [comment]
Hi @kadirbeytorun , unfortunately the memory hogging part is the attention computation, which is around 8GB. I think there is no easy way to make it compatible with 4GB without heavily downsample the image or changing the network architecture.

I have some ideas which can alleviate the memory constraint by changing the network a little. I am still experimenting to see if the performance drops or not. I can push the new code up as a separate branch or simpley as a new repo (not sure which one is the best yet). I will update you once I have something.

**Comment by maliksyria** [comment]
hello @mli0603 
I have a smillar issue on Jetson Xavier AGX with memory usage and I can add that it reach to +12 GB while doing the inference code example on KITTI (which leads to failure of the code). 
can you please share your solution of the code that use less memory [https://yadi.sk/i/8J8RMvi6H3s9Kg](url)

**Comment by maliksyria** [comment]
hello @mli0603 
I have a similar issue on Jetson Xavier AGX with memory usage and I can add that it reach to +12 GB while doing the inference code example on KITTI (which leads to failure of the code). 
can you please share your solution of the code that use less memory
this is the stats of usage 16.1 GB of memory  [https://yadi.sk/i/8J8RMvi6H3s9Kg](url)

**Comment by mli0603** [comment]
hi @maliksyria 

Your link doesn't work for me. I asusme the stat is from COLAB? I do see the same stat on COLAB. I guess (not super sure) the 16.1 GB of memory is because all variables in the notebook are saved during the forwared pass, which leads to additional 5GB somewhere. I ran via terminal script and monitored with `nvidia-smi`, and it reported 11GB memory at peak. Are you able to run it in terminal?

If 11 GB memory is still too much, the easiest way now is to set `downsample` argument to 4. In theory, this will reduce memory requirement to ~5GB,

I am looking into architecture changes now to see if this can be resolved. If so, I will update it here.

**Comment by maliksyria** [comment]
Hi @mli0603 
Thanks for answer, no actually it's not from COLAB. I did not use it, because that I have a pretty good GPU with my Jetosn Xavier AGX. the picture was stats from inside my Xavier regarding memory using, this is the screenshot on Dropbox [](https://www.dropbox.com/s/i430orz6k739c7f/image_2020-12-05_011008.png?dl=0 ).
I could not be able to run, PyTorch gives just the word "killed" in the terminal when it's doing the inferring command `output = model(input_data)` without any other reason to explain why, but I suppose it is related to memory issues (maximum usage of available 16 GB) as I have all requirements are set and installed.
Regarding your idea of setting `downsample` as 4, I'll try it soon, and give you feedback.

**Comment by mli0603** [comment]
I have made some changes (see pull request #7) for a slight more efficient implementation. Overall the memory saving is around 1.3G for KITTI, which reduces the requirement for KITTI to ~9GB. For now, I think this is the best I can do without needing to retrain the model (so the paper result is still valid), unless people spot something else for improvement. So let me know if you see something ;)

That being said, I know it is still a lot of memory for inference. This is really due to my naive implementation when I started the project (sigh...). I am working on a more efficient model and I hope it will work (cannot promise so far ;p)

**Comment by mli0603** [comment]
Hello @maliksyria @kadirbeytorun, as I promised, I have implemented a light-weight version of STTR [here](https://github.com/mli0603/stereo-transformer/tree/sttr-light) with some performance drop. The model is approximately **3x** memory efficient and **4x** faster. 

However, the performance drop is probably within confidence interval so they may actually perform the same in real world scenario. You can checkout the performance comparison [here](https://github.com/mli0603/stereo-transformer#expected-result).
