### ISSUE TITLE
Question about Self Attention

### ISSUE THREAD

**Issue by Frost-Yang-99** [mli0603/stereo-transformer#47]
Hi, I have a question about the TransformerSelfAttnLayer. I see you concat left feature and right feature, and then send them to the self-attention. According to my understanding, self-attention should only care about left feature (or right feature), but will such concat introduce right feature to left feature during the self-attention, just like cross-attention?

**Comment by mli0603** [comment]
Hi @Frost-Yang-99 

Good question. The information actually won't propagate between left and right images. Because the concatenation dimension is actually along the batch dimension as shown in [this line](https://github.com/mli0603/stereo-transformer/blob/f07b1ee8ced1c36e10630401688a06e355056e56/module/transformer.py#L107). The attention will not be leaked to that dimension :D
