### ISSUE TITLE
Selection of SCARED dataset

### ISSUE THREAD

**Issue by SuperAKK** [mli0603/stereo-transformer#6]
Hello!

That's an excellent job, thanks for sharing.

The paper mentioned that 315 pictures of the SCARED data set were selected. I want to know how did you select them? 

And have you noticed that the calibration parameters of the fourth and fifth data sets are incorrect?

The  interpolated depth and the video frame seem to be misaligned...

**Comment by mli0603** [comment]
Hi @SuperAKK, thanks for reaching out. 

I directly sampled the images every 50 frames to avoid double counting of similar scenes. I also excluded images that have fewer than 5% valid dispairties. Because the depth are interpolated from keyframes, therefore there are cases only few (e.g. 2 or 3) pixels have valid disparity. Then you get 100% or 0% for 3px error (because the samples are too few), which does not make sense to be included in the statistics. 

And you are correct, the 4th and 5th data set are very off... I think the result from dataset 1,2,3 is more reliable since the calibration parameter is reasonable. Therefore, for a more proper comparison, you should leave those ones out. I hope this helps.
